version: 2.1
orbs:
  gh: circleci/github-cli@2.1.0

workflows:
  version: 2
  prebuild-build-predeploy-deploy:
    jobs:
      - prebuild
      - build:
          context: github-credentials
          requires:
            - prebuild
      - predeploy:
          requires:
            - build
      - gh/release:
          context: github-credentials
          filters:
            branches:
              only: master
          requires:
            - predeploy
          title: Circle CI release
          tag: v$MVN_VERSION
          files: target/ebx-linkedin-sdk-${MVN_VERSION}*.jar
          notes-file: CHANGELOG.md

jobs:
  prebuild:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: 
          name: "What branch am I on?"
          command: echo "Source branch = ${CIRCLE_BRANCH}"
      - run:
          name: "Test non-present variable"
          command: if [ "$MISSING_VAR" != "" ]; then echo $MISSING_VAR; else echo "Variable missing"; fi
      - run:
          name: "Import GPG keys"
          command: if [ "$GPG_SECRET_KEYS" != "" ]; then echo $GPG_SECRET_KEYS; else echo "Variable missing"; fi
      - run:
          name: "Import GPG owner trust"
          command: echo $GPG_OWNERTRUST
      - run:
          name: "Source scripts"
          command: source buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh && source buildscripts/validateBuild.sh
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    environment:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    steps:
      - checkout
      - run:
          name: "Run build script"
          command: bash buildscripts/build.sh
      - run:
          name: "If build failure"
          command: cat target/surefire-reports/*.txt
          when: on_fail
  predeploy:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      # Set up git user name and tag this commit
      - run: |
          git config --local user.name "MarcFletcher"
          git config --local user.email "marc@echobox.com"
          export DEPLOY_TAG=v$MVN_VERSION
          git tag $DEPLOY_TAG
  gh/release:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - run: |
          echo "Deploying to github releases..."
