version: 2.1
orbs:
  gh: circleci/github-cli@2.1.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prebuild:
          context: 
            - Open Source Release Credentials
            - Non-sensitive Env Vars
      - build:
          context: 
            - Open Source Release Credentials
            - Non-sensitive Env Vars
          requires:
            - prebuild
      - predeploy:
          context: Non-sensitive Env Vars
          requires:
            - build

jobs:
  prebuild:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: 
          name: "What branch am I on?"
          command: export SOURCE_BRANCH_NAME=$CIRCLE_BRANCH
      - run:
          name: "Export version & Validate build"
          command: source buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh && source buildscripts/validateBuild.sh
  build:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run:
          name: "Run build/deploy scripts"
          command: source buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh && source buildscripts/build.sh
      - run:
          name: "If failure"
          command: cat target/surefire-reports/*.txt
          when: on_fail
  predeploy:
    machine:
      image: ubuntu-2004:2022.07.1
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" != "$DEV_BRANCH" ] && [ "$CIRCLE_BRANCH" != "$RELEASE_BRANCH" ]; then
              circleci-agent step halt
          fi
      - run: 
          name: "Export maven version"
          command: source buildscripts/exportMVNVersionWithSnapshotIfNotARelease.sh
      # Set up git user name and tag this commit
      - run: |
          git config --local user.name "MarcFletcher"
          git config --local user.email "marc@echobox.com"
          export DEPLOY_TAG=v$MVN_VERSION
          git tag $DEPLOY_TAG
